project_name: fairOS-dfs

release:
  prerelease: auto

builds:
  - id: linux-cli
    main: ./cmd/dfs
    binary: fairOS-dfs
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairdatasociety/fairOS-dfs.commit={{ .ShortCommit }}
      - -X github.com/fairdatasociety/fairOS-dfs.versions={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
        - 7
  - id: darwin-cli
    main: ./cmd/dfs
    binary: fairOS-dfs
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairdatasociety/fairOS-dfs.commit={{ .ShortCommit }}
      - -X github.com/fairdatasociety/fairOS-dfs.versions={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: windows-cli
    main: ./cmd/dfs
    binary: fairOS-dfs
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairdatasociety/fairOS-dfs.commit={{ .ShortCommit }}
      - -X github.com/fairdatasociety/fairOS-dfs.versions={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - 386

archives:
  - files:
      - README.md
      - LICENSE
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"