project_name: fairOS-dfs

release:
  prerelease: auto

builds:
  - id: linux-cli
    main: ./cmd/dfs
    binary: fairOS-dfs
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairdatasociety/fairOS-dfs.commit={{ .ShortCommit }}
      - -X github.com/fairdatasociety/fairOS-dfs.versions={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
        - 7
  - id: darwin-cli
    main: ./cmd/dfs
    binary: fairOS-dfs
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairdatasociety/fairOS-dfs.commit={{ .ShortCommit }}
      - -X github.com/fairdatasociety/fairOS-dfs.versions={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: windows-cli
    main: ./cmd/dfs
    binary: fairOS-dfs
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/fairdatasociety/fairOS-dfs.commit={{ .ShortCommit }}
      - -X github.com/fairdatasociety/fairOS-dfs.versions={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - 386

snapshot:
  name_template: "{{.Tag}}-snapshot"
archives:
  - replacements:
        386: i386
        amd64: x86_64
    name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    builds:
      - linux
      - windows
      - darwin-amd64
      - darwin-arm64