FROM alpine:3.15

ARG CONFIG
ENV CONFIG=$CONFIG

RUN addgroup -g 10000 fds
RUN adduser -u 10000 -G fds -h /home/fds -D fds

USER fds
RUN if [ -n "$CONFIG" ]; then  echo -e "$CONFIG" > ~/.dfs.yaml; fi
EXPOSE 9090

COPY dfs /usr/local/bin/dfs

ENTRYPOINT ["dfs"]
